### ISSUE TITLE
Code release plan

### ISSUE THREAD

**Issue by xnuohz** [dinry/IURO#1]
Hello, thanks for this awesome work, is there any plans to make the code and datasets open?

**Comment by dinry** [comment]
yes, the code will be published, but our private dataset can not be opened due to some reasons. Meanwhile I will run the source code in ZhihuRec dataset.

**Comment by xnuohz** [comment]
Thank you:)

**Comment by dinry** [comment]
I have uploaded the source code. But the data processing (data_prepare.py) and prediction of model (online_serving.py) are still empty, and I am rewriting them and they will be uploaded in three days.
